### ISSUE TITLE
GPL violation

### ISSUE THREAD

**Issue by feanor80** [svnpenn/rosso#2]
Hey,

Obviously, core parts of FATSort (http://fatsort.sourceforge.net/) were used in rosso. The GPL 2.0 licence texts have been removed from the source code files, hiding the original copyright.

As the copyright owner and main developer of FATsort I ask you to fix the license and copyright issue. The MPL license that rosso uses is not compatible with GPL. You will have to use GPL if you want to base rosso on FATsort code. 

Thanks and regards
Boris

**Comment by svnpenn** [comment]
@feanor80 sorry but that is not going to happen - some of the code here might appear to be similar to fatsort - of course this makes sense because both programs do the same thing

however the key difference is that Rosso works with Windows, while Fatsort does not - i approached the Fatsort author and was rebuffed:

> From: fatsort@formenos.de
>
> Subject: Re: Fatsort Windows
>
> I thought about porting fatsort for Windows some time ago. Finally, I decided that I don't want to support it since file system handling is different in Windows and I don't want to perform testing for Linux, Unix AND Windows for every release. Fatsort was written for Linux.
>
> I would have to look into Windows API before I could say what needs to be changed in the source code. You would definitely have to implement a separate file system read write operation for Windows.

so i authored it myself - as i am the sole author of this sofware - i would say that i have control over the license - perhaps you can write windows support for fatsort and everyone will be happy - note that i do not wish to discuss this further - but if you insist i can be reached `svnpenn at gmail dot com` - cheers
